server.port: 8081

spring:
  application.name: caradvertiser-service
  datasource:
    url: jdbc:h2:mem:testdb;
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: true
  h2:
    console:
      enabled: true

SECRET_KEY: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855