INSERT INTO usertable (id, username, email, password) VALUES (1, 'testuser1', 'test1@email.com', '$2a$10$wDNuIObqGPH2Dm.50yfJleNFejXv7Gj.d3kXjn5FMGB1/NroVWARi')
INSERT INTO usertable (id, username, email, password) VALUES (2, 'testuser2', 'test2@email.com', '$2a$10$t6oXqV6iXLePs.sBru/itOzEVhIA7v168ppD3yKRqwYEDXQKxI0uq')
INSERT INTO usertable (id, username, email, password) VALUES (3, 'testuser3', 'test3@email.com', '$2a$10$Pe1ALNoHunbcFQ1Gz2b4r.tPtlPUTl8HHisR02gDJma0Nrw0tile6')
INSERT INTO usertable (id, username, email, password) VALUES (4, 'testuser4', 'test4@email.com', '$2a$10$TdmbU61Nni5g7uuCWk1r2e//gknFMjAXVavT2exQH380QrVXPtcVG')
INSERT INTO usertable (id, username, email, password) VALUES (5, 'testuser5', 'test5@email.com', '$2a$10$sXE3ttjfIi15Gpt5GOMCWu9CNzKjxXPjwfJs4gzsQK7DCa8akCBRq')

INSERT INTO advertisement (id, username, brand, type, description, price) VALUES (1, 1, 'Toyota', 'SUV', 'A spacious and reliable SUV for family adventures.', 35000)
INSERT INTO advertisement (id, username, brand, type, description, price) VALUES (2, 3, 'Toyota', 'Sedan', 'A sleek and fuel-efficient sedan for city driving.', 25000)
INSERT INTO advertisement (id, username, brand, type, description, price) VALUES (3, 4, 'Toyota', 'Truck', 'A rugged truck built for heavy-duty hauling.', 40000)
INSERT INTO advertisement (id, username, brand, type, description, price) VALUES (4, 1, 'Honda', 'SUV', 'An agile and comfortable SUV for urban and off-road trips.', 32000)
INSERT INTO advertisement (id, username, brand, type, description, price) VALUES (5, 2, 'Honda', 'Sedan', 'A stylish sedan offering a smooth and enjoyable ride.', 27000)
INSERT INTO advertisement (id, username, brand, type, description, price) VALUES (6, 1, 'Honda', 'Hatchback', 'A compact hatchback with impressive fuel economy.', 22000)
INSERT INTO advertisement (id, username, brand, type, description, price) VALUES (7, 3, 'Ford', 'Truck', 'A powerful truck designed to tackle any job with ease.', 38000)
INSERT INTO advertisement (id, username, brand, type, description, price) VALUES (8, 1, 'Ford', 'SUV', 'A versatile SUV perfect for both daily commuting and weekend getaways.', 33000)
INSERT INTO advertisement (id, username, brand, type, description, price) VALUES (9, 4, 'Ford', 'Convertible', 'An exhilarating convertible that brings the thrill of open-air driving.', 39000)
INSERT INTO advertisement (id, username, brand, type, description, price) VALUES (10, 5, 'Chevrolet', 'Sedan', 'A reliable sedan offering a blend of performance and comfort.', 26000)
INSERT INTO advertisement (id, username, brand, type, description, price) VALUES (11, 5, 'Chevrolet', 'Truck', 'A dependable truck ready to handle tough tasks with confidence.', 37000)
INSERT INTO advertisement (id, username, brand, type, description, price) VALUES (12, 3, 'Chevrolet', 'SUV', 'A family-friendly SUV with advanced safety features and spacious interior.', 36000)
INSERT INTO advertisement (id, username, brand, type, description, price) VALUES (13, 4, 'BMW', 'Sedan', 'An elegant sedan that combines luxury with sporty performance.', 50000)
INSERT INTO advertisement (id, username, brand, type, description, price) VALUES (14, 5, 'BMW', 'Coupe', 'A sleek coupe designed for those who demand style and excitement.', 55000)