# API Template to extend when a service is created based on this archetype.
# Do not create a new .yml file next to this, rather use this as the main descriptor.

openapi: "3.0.3"
info:
  version: 1.0.0
  title: Microservice

servers:
  - url: http://localhost:8081

paths:

# ==============================================================================
# Car Advertisement
# ==============================================================================

  /api/v1/ad/{id}:
    get:
      tags:
        - caradvertiser
      operationId: getAd
      description: Get an existing Advertisement
      parameters:
        - name: id
          in: path
          required: true
          description: Id of the Advertisement
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Get back a single Advertisement view (Dto)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvertisementDto'
    delete:
      tags:
        - caradvertiser
      operationId: deleteAd
      description: Delete Advertisement corresponding to the given id. Only the Advertisement owner can delete the Advertisement.
      parameters:
        - name: id
          in: path
          required: true
          description: Id of the Advertisement
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Get back a deleted Advertisement view (Dto)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvertisementDto'

  /api/v1/ad:
    post:
      tags:
        - caradvertiser
      operationId: createAd
      description: Create an Advertisement
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/AdvertisementDto'
      responses:
        200:
          description: RegisterResponse which contains the id of the created Advertisement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdRegisterResponseDto'

  /api/v1/ad/search:
    get:
      tags:
        - caradvertiser
      operationId: search
      description: Returns every Advertisement that matches the requested Filter
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/FilterDto'
      responses:
        200:
          description: AdvertisementDtos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilterResultDto'

# ==============================================================================
# Authentication
# ==============================================================================

  /api/v1/auth/signup:
    post:
      tags:
        - authentication
      operationId: signup
      description: Sign up to the System
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        200:
          description: UserDto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'

  /api/v1/auth/login:
    post:
      tags:
        - authentication
      operationId: login
      description: Login to the System
      requestBody:
        required: true
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        200:
          description: LoginDto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponseDto'

components:
  schemas:
    AdvertisementDto:
      required:
        - brand
        - type
        - description
        - price
      properties:
        id:
          type: integer
          format: int64
          description:
            The technical id
        brand:
          type: string
          maxLength: 20
          minLength: 2
        type:
          type: string
          maxLength: 20
          minLength: 2
        description:
          type: string
          maxLength: 200
          minLength: 2
        price:
          type: integer
          format: int64
          maximum: 9999999999

    AdRegisterResponseDto:
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          description:
            The technical id of the registered Advertisement

    UserDto:
      required:
        - username
        - email
        - password
      properties:
        id:
          type: integer
          format: int64
          description:
            The technical id
        username:
          type: string
          maxLength: 50
          minLength: 2
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8

    LoginDto:
      required:
        - username
        - password
      properties:
        username:
          type: string
          maxLength: 50
          minLength: 2
        password:
          type: string
          minLength: 8

    AuthenticationResponseDto:
      required:
        - accessToken
        - refreshToken
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string

    FilterDto:
      properties:
        page:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        brand:
          type: string
          maxLength: 20
          minLength: 2
        type:
          type: string
          maxLength: 20
          minLength: 2
        price:
          type: integer
          format: int64
          maximum: 9999999999

    FilterResultDto:
      properties:
        page:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        ads:
          type: array
          items:
            $ref: '#/components/schemas/AdvertisementDto'
        totalElements:
          type: integer
          format: int64


